apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skiff.fullname" . }}
  labels:
    {{- include "skiff.labels" . | nindent 4 }}
data:
  DATABASE_URL: "file:///app/pg_data"
  {{- range $k, $v := .Values.config }}
  {{- if $v }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
