import { env } from "../env/index.js";

const MS_PER_DAY = 24 * 60 * 60 * 1000;

export const SLEEP_CONSOLIDATE_LOOKBACK_MS =
  env.SLEEP_CONSOLIDATE_LOOKBACK_DAYS * MS_PER_DAY;
export const SLEEP_CONSOLIDATE_MAX_USERS = env.SLEEP_CONSOLIDATE_MAX_USERS;
export const SLEEP_CONSOLIDATE_MIN_FACTS = env.SLEEP_CONSOLIDATE_MIN_FACTS;

export const SLEEP_DEDUPE_SIMILARITY = env.SLEEP_DEDUPE_SIMILARITY;
export const SLEEP_MAX_TOPICS = env.SLEEP_MAX_TOPICS;
export const SLEEP_MAX_MERGES_PER_RUN = env.SLEEP_MAX_MERGES_PER_RUN;

export const SLEEP_CLUSTER_THRESHOLD = env.SLEEP_CLUSTER_THRESHOLD;
export const SLEEP_MIN_CLUSTER_SIZE = env.SLEEP_MIN_CLUSTER_SIZE;
export const SLEEP_MAX_CLUSTERS_PER_RUN = env.SLEEP_MAX_CLUSTERS_PER_RUN;
export const SLEEP_MAX_SAMPLES = env.SLEEP_MAX_SAMPLES;
export const SLEEP_NEW_TOPIC_OVERLAP_THRESHOLD =
  env.SLEEP_NEW_TOPIC_OVERLAP_THRESHOLD;
export const SLEEP_SYNTHESIZE_LOOKBACK_MS =
  env.SLEEP_SYNTHESIZE_LOOKBACK_DAYS * MS_PER_DAY;

export const SLEEP_REFLECT_LOOKBACK_MS =
  env.SLEEP_REFLECT_LOOKBACK_DAYS * MS_PER_DAY;
export const SLEEP_REFLECT_MAX_MESSAGES = env.SLEEP_REFLECT_MAX_MESSAGES;
export const SLEEP_REFLECT_MIN_CONFIDENCE = env.SLEEP_REFLECT_MIN_CONFIDENCE;
export const SLEEP_REFLECT_MAX_ADDENDA_PER_RUN =
  env.SLEEP_REFLECT_MAX_ADDENDA_PER_RUN;

export const SLEEP_PROPOSE_LOOKBACK_MS =
  env.SLEEP_PROPOSE_LOOKBACK_DAYS * MS_PER_DAY;
export const SLEEP_PROPOSE_MAX_USER_MESSAGES =
  env.SLEEP_PROPOSE_MAX_USER_MESSAGES;
export const SLEEP_PROPOSE_MIN_CONFIDENCE = env.SLEEP_PROPOSE_MIN_CONFIDENCE;

export const SLEEP_MAX_ADDENDA_PER_SCOPE = env.SLEEP_MAX_ADDENDA_PER_SCOPE;
